src/Entity/Memory.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MemoryRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use App\Entity\Picture;

#[ORM\Entity(repositoryClass: MemoryRepository::class)]
class Memory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['get_memory'])]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 50,
        minMessage: 'Le titre doit comporter au moins {{ limit }} caractères.',
        maxMessage: 'Le titre ne peut pas dépasser {{ limit }} caractères.',
    )]
    #[Groups(['get_memory'])]
    private ?string $title = null;
  
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 10,
        max: 64000,
        minMessage: 'Le contenu doit comporter au moins {{ limit }} caractères.',
        maxMessage: 'Le contenu ne peut pas dépasser {{ limit }} caractères.',
    )]
    #[Groups(['get_memory'])]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups(['get_memory'])]
    private ?\DateTimeInterface $picture_date = null;

    #[ORM\Column(length: 2000)]
    #[Groups(['get_memory'])]
    private ?string $main_picture = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publishedAt = null;

    #[ORM\Column]
    
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;
   
    #[ORM\ManyToOne(inversedBy: 'memories')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['get_memory'])]
    private ?Location $location = null;

    #[ORM\OneToMany(mappedBy: 'memory', targetEntity: Picture::class, orphanRemoval: true)]
    #[Groups(['get_memory'])]
    private Collection $picture;

    #[ORM\ManyToOne(inversedBy: 'memories')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['get_memory'])]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'memories')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['get_memory'])]
    private ?Place $place = null;

    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
        $this->picture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPictureDate(): ?\DateTimeInterface
    {
        return $this->picture_date;
    }

    public function setPictureDate(\DateTimeInterface $picture_date): static
    {
        $this->picture_date = $picture_date;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(string $main_picture): static
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeImmutable $publishedAt): static
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }


    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPicture(): Collection
    {
        return $this->picture;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->picture->contains($picture)) {
            $this->picture->add($picture);
            $picture->setMemory($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->picture->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getMemory() === $this) {
                $picture->setMemory(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): static
    {
        $this->place = $place;

        return $this;
    }
}

src/Controller/Api/MemoryController.php
<?php

namespace App\Controller\Api;

use DateTime;
use App\Entity\Place;
use App\Entity\Memory;
use DateTimeImmutable;
use App\Entity\Location;
use App\Service\FileUploader;
use OpenApi\Attributes as OA;
use App\Service\MemoryProcessor;
use App\Repository\UserRepository;
use App\Repository\PlaceRepository;
use App\Repository\MemoryRepository;
use App\Repository\LocationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Nelmio\ApiDocBundle\Annotation\Model;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * This controller groups together all the methods that manage memories.
 * One method displays all memories.
 * One displays a single memory.
 * One displays the last and latest three memories created.
 * One displays two random memory pictures: The pictures of an old and a recent memory of a place with the same address. Before/after pictures.
 * Two methods create a memory:
 * -> The first one creates a memory from an existing locality and creates the name and type of the place if the existing ones are not suitable for this memory.
 * -> The second one creates a memory and a new locality as well as the name and type of the corresponding place.
 * Another one updates a memory with its identifier by adding, modifying or deleting additional photos.
 * A final one deletes a memory by its identifier and the data assigned to it.
 */
class MemoryController extends AbstractController
{

    private $fileUploader;
    private $memoryRepository;
    private $memoryProcessor;

    public function __construct(FileUploader $fileUploader, MemoryRepository $memoryRepository, MemoryProcessor $memoryProcessor)
    {
        $this->fileUploader = $fileUploader;
        $this->memoryRepository = $memoryRepository;
        $this->memoryProcessor = $memoryProcessor;
    }


    /**
     * Display all memories
     * 
     * @param MemoryRepository $memoryRepository
     * @return Response
     */
    #[Route('/api/memories', methods: ['GET'])]
    #[OA\Response(
        response: 200,
        description: 'Returns the memory list',
        content: new OA\JsonContent(
            type: 'array',
            items: new OA\Items(ref: new Model(type: Memory::class, groups: ['get_memory', 'get_location', 'get_place', 'get_user', 'get_picture'])),
            example: [
                [
                    "id" => 1,
                    "title" => "Le Panthéon en 1792",
                    "content" => "Le Panthéon en 1792, avec La Renommée en son sommet.n",
                    "picture_date" => "1792-01-01T00:00:00+00:00",
                    "main_picture" => "fileName.jpg",
                    "location" => [
                        "id" => 1,
                        "area" => "Île-de-France",
                        "department" => "Paris",
                        "district" => "Quartier latin",
                        "street" => "28 place du Panthéon",
                        "city" => "Paris",
                        "zipcode" => 75005,
                        "latitude" => "48.84619800",
                        "longitude" => "2.34610500"
                    ],
                    "picture" => [
                        [
                        "id" => 1,
                        "picture" => "filename.jpg",
                        ],
                        [
                            "id" => 2,
                            "picture" => "filename.jpg",
                            ],
                       
                        ],
                    "user" => [
                        "id" => 1,
                        "firstname" => "Aurélien",
                        "lastname" => "ROUCHETTE-MARET",
                        "email" => "aurelien.rouchette@orange.fr",
                        "roles" => [
                            "ROLE_USER",
                            "ROLE_ADMIN"
                        ]
                    ],
                    "place" => [
                        "id" => 1,
                        "name" => "Le Panthéon",
                        "type" => "Mausolée"
                    ]
                ],
                [
                    "id" => 2,
                    "title" => "Le Panthéon de nos jours",
                    "content" => "Le Panthéon vu de la tour Montparnasse en 2016.",
                    "picture_date" => "2016-01-01T00:00:00+00:00",
                    "main_picture" => "fileName.jpg",
                    "location" => [
                        "id" => 1,
                        "area" => "Île-de-France",
                        "department" => "Paris",
                        "district" => "Quartier latin",
                        "street" => "28 place du Panthéon",
                        "city" => "Paris",
                        "zipcode" => 75005,
                        "latitude" => "48.84619800",
                        "longitude" => "2.34610500"
                    ],
                    "picture" => [
                        [
                        "id" => 1,
                        "picture" => "filename.jpg",
                        ],
                        [
                            "id" => 2,
                            "picture" => "filename.jpg",
                            ],
                       
                        ],
                    "user" => [
                        "id" => 1,
                        "firstname" => "Aurélien",
                        "lastname" => "ROUCHETTE-MARET",
                        "email" => "aurelien.rouchette@orange.fr",
                        "roles" => [
                            "ROLE_USER",
                            "ROLE_ADMIN"
                        ]
                    ],
                    "place" => [
                        "id" => 1,
                        "name" => "Le Panthéon",
                        "type" => "Mausolée"
                    ]
                ],
            ]
        )
    )]
    #[OA\Tag(name: 'memory')]
    public function index(MemoryRepository $memoryRepository)
    {
        $memories = $memoryRepository->findAll();
      
        return $this->json($memories, 200, [], ['groups' => ['get_memory', 'get_location', 'get_place', 'get_user', 'get_picture']]);
    }

     /**
     * Route qui permet de récupérer l'ensemble des souvenirs associés avec une image avant/après
     */
    #[Route('/api/memorieswithtwopictures', methods: ['GET'])]
    #[OA\Response(
        response: 200,
        description: 'Returns the memory list with two pictures after/before',
        content: new OA\JsonContent(
            type: 'array',
            items: new OA\Items(ref: new Model(type: Memory::class, groups: ['get_memory', 'get_location', 'get_place', 'get_user', 'get_picture'])),
            example: [
                [
                    "id" => 1,
                    "title" => "Le Panthéon en 1792",
                    "content" => "Le Panthéon en 1792, avec La Renommée en son sommet.n",
                    "picture_date" => "1792-01-01T00:00:00+00:00",
                    "main_picture" => "fileName.jpg",
                    "compare_picture" => "fileName.jpg",
                    "location" => [
                        "id" => 1,
                        "area" => "Île-de-France",
                        "department" => "Paris",
                        "district" => "Quartier latin",
                        "street" => "28 place du Panthéon",
                        "city" => "Paris",
                        "zipcode" => 75005,
                        "latitude" => "48.84619800",
                        "longitude" => "2.34610500"
                    ],
                    "picture" => [
                        [
                        "id" => 1,
                        "picture" => "filename.jpg",
                        ],
                        [
                            "id" => 2,
                            "picture" => "filename.jpg",
                            ],
                       
                        ],
                    "user" => [
                        "id" => 1,
                        "firstname" => "Aurélien",
                        "lastname" => "ROUCHETTE-MARET",
                        "email" => "aurelien.rouchette@orange.fr",
                        "roles" => [
                            "ROLE_USER",
                            "ROLE_ADMIN"
                        ]
                    ],
                    "place" => [
                        "id" => 1,
                        "name" => "Le Panthéon",
                        "type" => "Mausolée"
                    ]
                ],
                [
                    "id" => 2,
                    "title" => "Le Panthéon de nos jours",
                    "content" => "Le Panthéon vu de la tour Montparnasse en 2016.",
                    "picture_date" => "2016-01-01T00:00:00+00:00",
                    "main_picture" => "fileName.jpg",
                    "compare_picture" => "fileName.jpg",
                    "location" => [
                        "id" => 1,
                        "area" => "Île-de-France",
                        "department" => "Paris",
                        "district" => "Quartier latin",
                        "street" => "28 place du Panthéon",
                        "city" => "Paris",
                        "zipcode" => 75005,
                        "latitude" => "48.84619800",
                        "longitude" => "2.34610500"
                    ],
                    "picture" => [
                        [
                        "id" => 1,
                        "picture" => "filename.jpg",
                        ],

src/Controller/Back/MainController.php
<?php

namespace App\Controller\Back;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * Display backoffice home page
     *
     * @return Response
     */
    #[Route('/back', name: 'app_main')]
    public function index(): Response
    {
        return $this->render('back/main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }

    #[Route('/translation/{locale}', name: 'app_translation')]
    public function translation($locale, Request $request): Response
    {
        
        $request->getSession()->set('_locale', $locale);
      
        return $this->redirect($request->headers->get('referer'));
    }
}

src/Controller/Back/Sort/LocationSortController.php
<?php

namespace App\Controller\Back\Sort;

use App\Repository\LocationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/back/sort/location')]
class LocationSortController extends AbstractController
{
    /**
     * Location sorting management
     *
     * @param Request $request
     * @param LocationRepository $locationRepository
     * @return void
     */
    #[Route('/', name: 'app_sort_location_by', methods: ['GET'])]
    public function sortBy(Request $request, LocationRepository $locationRepository) {

        $order = $request->query->get('order', '');
        $selectedDirection = $request->query->get('selectedDirection', 'asc');

        $direction = in_array($selectedDirection, ['asc', 'desc']) ? $selectedDirection : 'asc';

        $locations = $locationRepository->findBy([], [$order => $direction]);

        return $this->render('back/location/index.html.twig', [
            'locations' => $locations,
        ]);
    }
}
?>

templates/back/memory/_delete_form.html.twig
<form class="form-group" method="post" action="{{ path('app_memory_delete', {'id': memory.id}) }}" onsubmit="return confirm('{{ 'deletion_confirmation'|trans }}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ memory.id) }}">
    <button class="btn btn-lg text-white mb-2 btn-danger btn-delete">
        {# Cell phone #}
        {# <div class="d-block d-sm-none"><i class="bi bi-trash3-fill"></i></div> #}
        {# Else #}
        <div class="d-block">{{ 'button.delete'|trans }}</div>   
    </button>
</form>

templates/back/memory/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="mb-5 mx-3">{{ 'memory.title.edit'|trans }}</h1>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    {# If you're on a cell phone #}
                    {# <div class="d-block d-sm-none">{{ include('back/memory/_form.html.twig', {'button_label': ' '|trans}) }}{# </div>  #}
                    {# Else #}
                    {# <div class="d-none d-sm-block"> #}
                    {{ include('back/memory/_form.html.twig', {'button_label': 'button.update'|trans}) }}
                    {# </div>  #}

                    <div class="col col-md-2 d-md-inline-block div-btn-delete">
                        {{ include('back/memory/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/back/memory/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center text-md-start">{{ 'memory.title.index'|trans }}</h1>

    <table class="table table-auto">
        <thead>
            <tr>
                <th class="col-1 text-center align-middle">Id
                    <a class="text-decoration-none" href="{{ path('app_sort_memory_by', {'order': 'id', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-numeric-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'id', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-numeric-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">{{ 'memory.article.title'|trans }}
                    <a href="{{ path('app_sort_memory_by', {'order': 'title', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-alpha-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'title', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-alpha-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">{{ 'memory.content'|trans }}</th>
                <th class="text-center align-middle">{{ 'memory.main_picture'|trans }}</th>
                <th class="text-center align-middle">{{ 'memory.picture_date'|trans }}
                    <a class="text-decoration-none" href="{{ path('app_sort_memory_by', {'order': 'picture_date', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-numeric-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'picture_date', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-numeric-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">{{ 'memory.place'|trans }}
                    <a href="{{ path('app_sort_memory_by', {'order': 'place', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-alpha-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'place', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-alpha-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">{{ 'memory.address'|trans }}
                    <a href="{{ path('app_sort_memory_by', {'order': 'location', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-alpha-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'location', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-alpha-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">{{ 'memory.user'|trans }}
                    <a href="{{ path('app_sort_memory_by', {'order': 'user', 'selectedDirection': 'asc'}) }}"><i class="bi bi-sort-alpha-up"></i></a>
                    <a href="{{ path('app_sort_memory_by', {'order': 'user', 'selectedDirection': 'desc'}) }}"><i class="bi bi-sort-alpha-down-alt"></i></a>
                </th>
                <th class="text-center align-middle">actions</th>
            </tr>
        </thead>
        <tbody>
        {# {% if order is defined and order is same as (('location') or ('place')) %} #}
        {% if order is defined and order in ['location', 'place'] %}
            {% if sortResults is not empty %}
                {% for sortResult in sortResults %}
                <tr>
                    <td class="text-center align-middle">{{ sortResult.id }}</td>
                    <td class="text-center align-middle">{{ sortResult.title }}</td>
                    <td class="text-center align-middle">{{ sortResult.content| slice(0,50) }}</td>
                    <td class="text-center align-middle"> <img src="{{ asset('assets/pictures/' ~ sortResult.main_picture) }}" class="img-thumbnail"></td>
                    <td class="text-center align-middle">{{ sortResult.picture_date ? sortResult.picture_date|date('Y-m-d') : '' }}</td>
                    <td class="text-center align-middle">{{ sortResult.placeName }} {{ sortResult.type }}</td>
                    <td class="text-center align-middle">{{ sortResult.street }} {{ sortResult.zipcode }} {{ sortResult.city }}</td>
                    <td class="text-center align-middle">{{ sortResult.userFirstName }} {{ sortResult.userLastName }}</td>
                    <td class="text-center align-middle">
                       <a href="{{ path('app_memory_show', {'id': sortResult.id}) }}" title= "{{ 'button.show'|trans }}" aria-label ="{{ 'button.show'|trans }}"><i class="bi bi-eye mx-2" style="font-size: 1.5rem; color:#0761ff;"></i></a>   
                       <a href="{{ path('app_memory_edit', {'id': sortResult.id}) }}" title= "{{ 'button.edit'|trans }}" aria-label ="{{ 'button.edit'|trans }}"><i class="bi bi-pencil-fill" style="font-size: 1.5rem; color: #ffc107;"></i></a>   
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="9">{{ 'no_records_found'|trans }}</td>
                </tr>
            {% endif %}
        {% else %}
            {% if memories is not empty %}
                {% for memory in memories %}
                <tr>
                    <td>{{ memory.id }}</td>
                    <td>{{ memory.title }}</td>
                    <td>{{ memory.content | slice(0,50) }}</td>
                    <td> <img src="{{ asset('assets/pictures/' ~  memory.mainPicture)}}"class="img-thumbnail"></td>
                    <td>{{ memory.pictureDate ? memory.pictureDate|date('Y-m-d') : '' }}</td>
                    <td>{{ memory.place.name }} - {{ memory.place.type }}</td>
                    <td>{{ memory.location.street }} {{ memory.location.zipcode }} {{ memory.location.city }}</td>
                    <td>{{ memory.user.firstname }} {{ memory.user.lastname }}</td>
                    <td>
                       <a href="{{ path('app_memory_show', {'id': memory.id}) }}" title= "{{ 'button.show'|trans }}" aria-label ="{{ 'button.show'|trans }}"><i class="bi bi-eye mx-2" style="font-size: 1.5rem; color:#0761ff;"></i></a>   
                       <a href="{{ path('app_memory_edit', {'id': memory.id}) }}" title= "{{ 'button.edit'|trans }}" aria-label ="{{ 'button.edit'|trans }}"><i class="bi bi-pencil-fill" style="font-size: 1.5rem; color: #ffc107;"></i></a>  
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="9">{{ 'no_records_found'|trans }}</td>
                </tr>
            {% endif %}
        {% endif %}
        </tbody>
    </table>
        {# If you're on a cell phone #}
            {# <div class="d-inline-block d-sm-none"><a class="btn btn-lg btn-success m-5" href="{{ path('app_memory_new') }}"><i class="bi bi-plus-square-fill"></i></a></div>
            <div class="d-inline-block d-sm-none"><a class="btn btn-lg btn-secondary text-white m-1" href="{{ path('app_main') }}"><i class="bi bi-backspace-fill"></i></a></div> #}
        {# Else #}
            <div class="d-md-inline-block d-block text-center vertical-align-middle mb-2 mx-md-5"><a class="btn btn-lg btn-dark-purple btn-mobile text-white" href="{{ path('app_memory_new') }}">{{ 'memory.new'|trans }}</a></div>
            <div class="d-md-inline-block d-block text-center vertical-align-middle mb-2"><a class="btn btn-lg btn-secondary btn-mobile text-white" href="{{ path('app_main') }}">{{ 'button.home'|trans }}</a></div>
{% endblock %}

templates/back/memory/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="mx-3 mb-5">{{ 'memory.title.new'|trans }}</h1>
    <div class="container">
		<div class="row">
			<div class="col">
                {{ include('back/memory/_form.html.twig') }}
            </div>
	    </div>  
	</div> 
{% endblock %}

templates/back/memory/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>{{ 'memory.title'|trans }}</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ memory.id }}</td>
			</tr>
			<tr>
				<th>{{ 'memory.article.title'|trans }}</th>
				<td>{{ memory.title }}</td>
			</tr>
			<tr>
				<th>{{ 'memory.content'|trans }}</th>
				<td>{{ memory.content }}</td>
			</tr>
			<tr>
				<th>{{ 'memory.main_picture'|trans }}</th>
				<td>{{ memory.mainPicture }}
					<img src="{{ asset('assets/pictures/' ~ memory.mainPicture) }}" class="img-thumbnail mx-5" alt="Main Picture"></td>
			</tr>
			<tr>
				<th>{{ 'memory.picture_date'|trans }}</th>
				<td>{{ memory.pictureDate ? memory.pictureDate|date('d-m-Y') : '' }}</td>
			</tr>
			<tr>
				<th>{{ 'memory.place'|trans }}</th>
				<td>{{ memory.place.name }}
					{{ memory.place.type }}
					<a class="mx-5 btn btn-secondary" href="{{ path('app_place_show', {'id': memory.place.id}) }}">{{ 'button.show'|trans }}</a>
				</td>


			</tr>
			<tr>
				<th>{{ 'memory.address'|trans }}</th>
				<td>{{ memory.location.street }}
					{{ memory.location.zipcode }}
					{{ memory.location.city }}
					<a class="mx-5 btn btn-secondary" href="{{ path('app_location_show', {'id': memory.location.id}) }}">{{ 'button.show'|trans }}</a>
				</td>
			</tr>
			<tr>
				<th>{{ 'memory.user'|trans }}</th>
				<td>{{ memory.user.firstname }}
					{{ memory.user.lastname }}</td>
			</tr>
			{% if memory.picture is not empty %}>
				{% for picture in memory.picture %}
					<tr>
						<th>{{ 'memory.additional_picture'|trans }}</th>
						<td>{{ picture.picture }}
							<img src="{{ asset('assets/pictures/' ~ picture.picture) }}" class="img-thumbnail mx-5" alt="Additional Picture"><a class="mx-5 btn btn-secondary" href="{{ path('app_picture_show', {'id': picture.id}) }}">{{ 'button.show'|trans }}</a></td>
					</tr>
				{% endfor %}
			{% endif %}
		</tbody>
	</table>
	<div class="row">

		<div class="col d-flex flex-column flex-md-row mx-3 my-2 align-items-md-start">
			<a class="btn btn-lg btn-secondary text-white d-inline-block mb-2 mx-md-3" href="{{ path('app_memory_index') }}">
				<div class="d-block">{{ 'button.back'|trans }}</div>
			</a>

			<a class="btn btn-lg btn-warning text-white" href="{{ path('app_memory_edit', {'id': memory.id}) }}">
				<div class="d-nblock">{{ 'button.edit'|trans }}</div>
			</a>
		</div>

	</div>

	<div class="px-3 col col-md-2 d-md-inline-block div-btn-delete">
		{{ include('back/memory/_delete_form.html.twig') }}
	</div>

{% endblock %}